package com.shresth.FrankenCloud.Entity;

import com.shresth.FrankenCloud.Entity.Enum.FileType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "files")
public class Files {

    @Id
    private ObjectId id;

    private ObjectId userId;
    private String fileName;
    private ObjectId parentFolderId; //null if root
    private Long fileSize;
    private FileType fileType;

    private Long shards;
    private Long parityShards;
    private String encryptionKey; //this is generated by userId, fileId, fileName, userEmail and salt.
    //We can use this key with hashed password to encrypt the file.
    private String iv; // this is imp for streamable decryption

    @CreatedDate
    private Date createdAt;
    @LastModifiedDate
    private Date updatedAt;
}
